version: '3.8'

services:

  app:
    build: ./app
    ports:
      - 8000:8000
    command: uvicorn server:app --host 0.0.0.0 --reload
    volumes:
      - ./${STORAGE_DIR}:/${STORAGE_DIR}
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - STORAGE_DIR=json_output_data
    depends_on:
      - redis

  worker:
    build: ./app
    command: celery --app worker.celery worker
    volumes:
      - ./${STORAGE_DIR}:/${STORAGE_DIR}
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - STORAGE_DIR=json_output_data
    depends_on:
      - app
      - redis

  redis:
    image: redis:6-alpine